name: treeify
description: A dart port of the treeify.js for console printing trees
version: 0.0.1-nullsafety.0
repository: https://github.com/Nolence/treeify

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3
