name: treeify
description: A dart port of the treeify.js for creating trees or directory structures to be printed to console
version: 0.0.1-nullsafety.2
repository: https://github.com/Nolence/treeify

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:

dev_dependencies:
  test: 1.16.0-nullsafety.16
  pedantic: ^1.10.0-nullsafety.3
