name: Dart CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: google/dart:dev

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: pub get

      - name: format
        run: dartfmt -n --set-exit-if-changed .

      - name: analyzer
        run: dartanalyzer --fatal-warnings --fatal-infos .

      - name: Run tests
        run: pub run test